-- Create a table for the Guestbook
create table guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table guestbook enable row level security;

-- Policy: Allow ANYONE to read entries (public read access)
create policy "Public guestbook are viewable by everyone."
  on guestbook for select
  using ( true );

-- Policy: Allow ANYONE to insert entries (public write access)
create policy "Anyone can insert a guestbook entry."
  on guestbook for insert
  with check ( true );
